# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2987a34650362095109d6228d2b5f62de5bc2eabe3381521fe69caef8dc0599d4da5f6d87d65c858ba7e4f7585a4650c4e46c11bec1f640e92cd900486f20f27

test:
  secret_key_base: ea081c2ae8b6d9723a6a74a1c99f92cb33313e1095b425d92cf8510b5cea26999f9dd37c0128ce432d9c6d2b83d0d46c06e3ef2dfc5456586ab19beba7920720

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
